-- Adding comprehensive vaccine data for all animal types
-- Insert sample vaccine data for common animals
INSERT INTO `tblmypets_vaccines` (`name`, `animal_type`, `vaccine_type`, `description`, `frequency`, `age_range`, `manufacturer`, `dosage`, `route`, `notes`) VALUES

-- Dog Vaccines (Core)
('Rabies', 'Dog', 'Core', 'Protects against rabies virus, a fatal neurological disease', 'Annual or 3-year', '12-16 weeks, then booster', 'Various', '1ml', 'Subcutaneous', 'Required by law in most areas'),
('Canine Distemper', 'Dog', 'Core', 'Protects against distemper virus affecting respiratory, GI, and nervous systems', 'Every 3 years', '6-8 weeks, boosters every 2-4 weeks until 16 weeks', 'Various', '1ml', 'Subcutaneous', 'Often combined with other vaccines (DHPP)'),
('Canine Parvovirus', 'Dog', 'Core', 'Protects against parvovirus causing severe GI illness', 'Every 3 years', '6-8 weeks, boosters every 2-4 weeks until 16 weeks', 'Various', '1ml', 'Subcutaneous', 'Highly contagious, especially dangerous for puppies'),
('Canine Adenovirus (Hepatitis)', 'Dog', 'Core', 'Protects against infectious canine hepatitis', 'Every 3 years', '6-8 weeks, boosters every 2-4 weeks until 16 weeks', 'Various', '1ml', 'Subcutaneous', 'Part of DHPP combination vaccine'),
('Canine Parainfluenza', 'Dog', 'Core', 'Protects against parainfluenza virus', 'Every 3 years', '6-8 weeks, boosters every 2-4 weeks until 16 weeks', 'Various', '1ml', 'Subcutaneous', 'Part of DHPP combination vaccine'),
('Canine Adenovirus-1 (Hepatitis)', 'Dog', 'Core', 'Protects against infectious canine hepatitis type 1', 'Every 3 years', '6-8 weeks, boosters every 2-4 weeks until 16 weeks', 'Zoetis', '1ml', 'Subcutaneous', 'Causes liver disease, often combined with other vaccines'),
('Canine Parvovirus Type 2c', 'Dog', 'Core', 'Protects against newer parvovirus variant', 'Every 3 years', '6-8 weeks, boosters every 2-4 weeks until 16 weeks', 'Various', '1ml', 'Subcutaneous', 'Newer strain coverage'),

-- Dog Vaccines (Non-Core/Lifestyle)
('Bordetella (Kennel Cough)', 'Dog', 'Non-Core', 'Protects against kennel cough complex', 'Every 6-12 months', '8 weeks and older', 'Various', '0.5ml', 'Intranasal/Subcutaneous', 'Recommended for dogs in boarding, grooming, or social settings'),
('Lyme Disease', 'Dog', 'Non-Core', 'Protects against Lyme disease transmitted by ticks', 'Annual', '12 weeks, booster 2-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'Recommended in endemic areas'),
('Canine Influenza H3N2', 'Dog', 'Non-Core', 'Protects against canine influenza virus H3N2', 'Annual', '6-8 weeks, booster 2-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'Recommended for social dogs'),
('Canine Influenza H3N8', 'Dog', 'Non-Core', 'Protects against canine influenza virus H3N8', 'Annual', '6-8 weeks, booster 2-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'Recommended for social dogs'),
('Leptospirosis', 'Dog', 'Non-Core', 'Protects against leptospirosis bacteria', 'Annual', '8 weeks, booster 2-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'Risk varies by geographic location'),
('Canine Leishmaniosis', 'Dog', 'Non-Core', 'Protects against leishmaniosis parasite', 'Annual', '6 months and older', 'Various', '1ml', 'Subcutaneous', 'For endemic areas'),
('Canine Herpesvirus-1', 'Dog', 'Non-Core', 'Protects against herpesvirus in breeding dogs', 'During pregnancy', 'Pregnant bitches only', 'Various', '1ml', 'Subcutaneous', 'For breeding females'),
('Rattlesnake Vaccine', 'Dog', 'Non-Core', 'Provides protection against rattlesnake venom', 'Annual', '4 months and older', 'Various', '1ml', 'Subcutaneous', 'For dogs in snake-endemic areas'),
('Canine Coronavirus', 'Dog', 'Non-Core', 'Protects against canine coronavirus causing GI upset', 'Annual', '6-8 weeks, booster 2-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'Mild disease, vaccine effectiveness debated'),
('Canine Adenovirus-2', 'Dog', 'Non-Core', 'Protects against respiratory form of adenovirus', 'Every 3 years', '6-8 weeks, boosters every 2-4 weeks until 16 weeks', 'Various', '1ml', 'Subcutaneous', 'Cross-protects against CAV-1'),
('Ehrlichiosis', 'Dog', 'Non-Core', 'Protects against Ehrlichia canis tick-borne disease', 'Annual', '12 weeks and older', 'Various', '1ml', 'Subcutaneous', 'For tick-endemic areas'),
('Babesiosis', 'Dog', 'Non-Core', 'Protects against Babesia canis parasite', 'Annual', '5 months and older', 'Various', '1ml', 'Subcutaneous', 'For areas with tick vectors'),
('Giardia', 'Dog', 'Non-Core', 'Protects against Giardia intestinal parasite', 'Annual', '8 weeks, booster 2-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'For high-risk environments'),
('Canine Papillomavirus', 'Dog', 'Non-Core', 'Protects against oral papillomavirus causing warts', 'Annual', '6 months and older', 'Merck', '1ml', 'Subcutaneous', 'For dogs with recurrent papillomas'),
('Canine Cyclic Neutropenia', 'Dog', 'Non-Core', 'Supportive treatment for cyclic neutropenia', 'As needed', 'Affected dogs', 'Various', '1ml', 'Subcutaneous', 'Rare genetic condition in Collies'),
('Canine Melanoma', 'Dog', 'Non-Core', 'Therapeutic vaccine for melanoma treatment', 'Series of 4 doses', 'Dogs with melanoma', 'Merial', '1ml', 'Intramuscular', 'Oncology therapeutic vaccine'),
('Canine Lymphoma', 'Dog', 'Non-Core', 'Therapeutic vaccine for lymphoma treatment', 'Series of doses', 'Dogs with lymphoma', 'Various', '1ml', 'Subcutaneous', 'Experimental cancer treatment'),
('Canine Minute Virus', 'Dog', 'Non-Core', 'Protects against canine minute virus', 'Annual', '8 weeks and older', 'Various', '1ml', 'Subcutaneous', 'Rare parvovirus-related infection'),
('Canine Oral Papillomavirus', 'Dog', 'Non-Core', 'Protects against oral warts', 'Annual', '6 months and older', 'Various', '1ml', 'Subcutaneous', 'For dogs prone to oral papillomas'),
('Canine Reovirus', 'Dog', 'Non-Core', 'Protects against reovirus respiratory infection', 'Annual', '8 weeks and older', 'Various', '1ml', 'Subcutaneous', 'Mild respiratory symptoms'),
('Canine Rotavirus', 'Dog', 'Non-Core', 'Protects against rotavirus causing diarrhea', 'Annual', '6-8 weeks, booster 2-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'Gastrointestinal protection'),

-- Cat Vaccines (Core)
('Feline Rabies', 'Cat', 'Core', 'Protects against rabies virus', 'Annual or 3-year', '12-16 weeks, then booster', 'Various', '1ml', 'Subcutaneous', 'Required by law in most areas'),
('Feline Panleukopenia (Distemper)', 'Cat', 'Core', 'Protects against feline panleukopenia virus', 'Every 3 years', '6-8 weeks, boosters every 3-4 weeks until 16 weeks', 'Various', '1ml', 'Subcutaneous', 'Often combined in FVRCP vaccine'),
('Feline Herpesvirus-1 (Rhinotracheitis)', 'Cat', 'Core', 'Protects against feline herpesvirus-1', 'Annual for high-risk, 3 years for low-risk', '6-8 weeks, boosters every 3-4 weeks until 16 weeks', 'Various', '1ml', 'Subcutaneous', 'Part of FVRCP combination'),
('Feline Calicivirus', 'Cat', 'Core', 'Protects against calicivirus causing respiratory disease', 'Annual for high-risk, 3 years for low-risk', '6-8 weeks, boosters every 3-4 weeks until 16 weeks', 'Various', '1ml', 'Subcutaneous', 'Part of FVRCP combination'),
('Feline Parvovirus', 'Cat', 'Core', 'Alternative name for panleukopenia virus', 'Every 3 years', '6-8 weeks, boosters every 3-4 weeks until 16 weeks', 'Various', '1ml', 'Subcutaneous', 'Same as panleukopenia vaccine'),

-- Cat Vaccines (Non-Core)
('Feline Leukemia Virus (FeLV)', 'Cat', 'Non-Core', 'Protects against feline leukemia virus', 'Annual', '8 weeks, booster 3-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'Core for young cats, recommended for outdoor cats'),
('Feline Immunodeficiency Virus (FIV)', 'Cat', 'Non-Core', 'Protects against feline immunodeficiency virus', 'Annual', '8 weeks, boosters at 10 and 12 weeks', 'Various', '1ml', 'Subcutaneous', 'For high-risk cats where available'),
('Chlamydia felis', 'Cat', 'Non-Core', 'Protects against chlamydial conjunctivitis', 'Annual', '9 weeks, booster 3-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'For multi-cat environments'),
('Bordetella bronchiseptica', 'Cat', 'Non-Core', 'Protects against bordetella respiratory infection', 'Annual', '4 weeks and older', 'Various', '0.5ml', 'Intranasal', 'For cats in shelters or multi-cat facilities'),
('Feline Bordetella', 'Cat', 'Non-Core', 'Protects against Bordetella bronchiseptica', 'Annual', '4 weeks and older', 'Various', '0.5ml', 'Intranasal', 'For multi-cat facilities'),
('Feline Giardia', 'Cat', 'Non-Core', 'Protects against Giardia intestinal parasite', 'Annual', '8 weeks, booster 3-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'For shelter environments'),
('Dermatophytosis (Ringworm)', 'Cat', 'Non-Core', 'Protects against fungal skin infection', 'Annual', '4 months and older', 'Various', '0.5ml', 'Subcutaneous', 'For high-risk cats'),
('Feline Infectious Peritonitis (FIP)', 'Cat', 'Non-Core', 'Protects against FIP coronavirus', 'Annual', '16 weeks and older', 'Various', '0.5ml', 'Intranasal', 'Limited effectiveness, controversial'),
('Feline Pneumonitis', 'Cat', 'Non-Core', 'Protects against Chlamydophila felis', 'Annual', '9 weeks, booster 3-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'Respiratory and eye infection'),
('Feline Syncytial Virus', 'Cat', 'Non-Core', 'Protects against feline syncytial virus', 'Annual', '8 weeks and older', 'Various', '1ml', 'Subcutaneous', 'Respiratory infection in young cats'),
('Feline Enteric Coronavirus', 'Cat', 'Non-Core', 'Protects against enteric coronavirus', 'Annual', '16 weeks and older', 'Various', '1ml', 'Subcutaneous', 'Mild gastrointestinal symptoms'),
('Feline Reovirus', 'Cat', 'Non-Core', 'Protects against feline reovirus', 'Annual', '8 weeks and older', 'Various', '1ml', 'Subcutaneous', 'Mild respiratory and enteric signs'),
('Feline Rotavirus', 'Cat', 'Non-Core', 'Protects against feline rotavirus', 'Annual', '6-8 weeks, booster 3-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'Diarrhea in young cats'),
('Feline Astrovirus', 'Cat', 'Non-Core', 'Protects against feline astrovirus', 'Annual', '8 weeks and older', 'Various', '1ml', 'Subcutaneous', 'Gastrointestinal infection'),
('Feline Norovirus', 'Cat', 'Non-Core', 'Protects against feline norovirus', 'Annual', '8 weeks and older', 'Various', '1ml', 'Subcutaneous', 'Gastrointestinal symptoms'),
('Feline Sapovirus', 'Cat', 'Non-Core', 'Protects against feline sapovirus', 'Annual', '8 weeks and older', 'Various', '1ml', 'Subcutaneous', 'Enteric calicivirus'),

-- Horse Vaccines (Core)
('Equine Tetanus', 'Horse', 'Core', 'Protects against tetanus bacteria', 'Annual', '4-6 months, booster 4-6 weeks later', 'Various', '1ml', 'Intramuscular', 'Essential for all horses'),
('Eastern Equine Encephalomyelitis (EEE)', 'Horse', 'Core', 'Protects against EEE virus', 'Annual', '4-6 months, booster 4-6 weeks later', 'Various', '1ml', 'Intramuscular', 'Often combined with WEE'),
('Western Equine Encephalomyelitis (WEE)', 'Horse', 'Core', 'Protects against WEE virus', 'Annual', '4-6 months, booster 4-6 weeks later', 'Various', '1ml', 'Intramuscular', 'Often combined with EEE'),
('West Nile Virus', 'Horse', 'Core', 'Protects against West Nile virus', 'Annual', '4-6 months, booster 4-6 weeks later', 'Various', '1ml', 'Intramuscular', 'Important in endemic areas'),
('Equine Rabies', 'Horse', 'Core', 'Protects against rabies virus', 'Annual', '4-6 months, then annual', 'Various', '1ml', 'Intramuscular', 'Required in many areas'),

-- Horse Vaccines (Non-Core)
('Strangles (Streptococcus equi)', 'Horse', 'Non-Core', 'Protects against strangles bacteria', 'Annual', '4-6 months, booster 2-4 weeks later', 'Various', '1ml', 'Intramuscular/Intranasal', 'For horses at risk of exposure'),
('Equine Herpesvirus-1 (EHV-1)', 'Horse', 'Non-Core', 'Protects against equine herpesvirus-1', 'Every 6 months', '4-6 months, booster 4-6 weeks later', 'Various', '1ml', 'Intramuscular', 'Important for breeding horses'),
('Equine Herpesvirus-4 (EHV-4)', 'Horse', 'Non-Core', 'Protects against equine herpesvirus-4', 'Every 6 months', '4-6 months, booster 4-6 weeks later', 'Various', '1ml', 'Intramuscular', 'Important for breeding horses'),
('Equine Influenza', 'Horse', 'Non-Core', 'Protects against equine influenza virus', 'Every 6 months', '4-6 months, booster 4-6 weeks later', 'Various', '1ml', 'Intramuscular', 'For horses in competition or travel'),
('Potomac Horse Fever', 'Horse', 'Non-Core', 'Protects against Neorickettsia risticii', 'Annual', '4-6 months, booster 3-4 weeks later', 'Various', '1ml', 'Intramuscular', 'For horses in endemic areas'),
('Equine Viral Arteritis (EVA)', 'Horse', 'Non-Core', 'Protects against equine arteritis virus', 'Annual', 'Stallions and high-risk horses', 'Various', '1ml', 'Intramuscular', 'Primarily for breeding stallions'),
('Anthrax', 'Horse', 'Non-Core', 'Protects against anthrax bacteria', 'Annual', '4 months and older', 'Various', '1ml', 'Subcutaneous', 'For endemic areas only'),
('Botulism', 'Horse', 'Non-Core', 'Protects against botulism toxin', 'Annual', '2-3 doses initially, then annual', 'Various', '1ml', 'Intramuscular', 'For high-risk areas'),
('Venezuelan Equine Encephalomyelitis (VEE)', 'Horse', 'Non-Core', 'Protects against VEE virus', 'Annual', '4-6 months, booster 4-6 weeks later', 'Various', '1ml', 'Subcutaneous', 'For travel to endemic areas'),
('Equine Protozoal Myeloencephalitis (EPM)', 'Horse', 'Non-Core', 'Protects against Sarcocystis neurona', 'Annual', '4-6 months, 3 doses 4 weeks apart', 'Various', '1ml', 'Intramuscular', 'For areas with opossums'),
('Pigeon Fever', 'Horse', 'Non-Core', 'Protects against Corynebacterium pseudotuberculosis', 'Annual', '4 months and older', 'Various', '1ml', 'Intramuscular', 'For endemic western US areas'),
('Equine Infectious Anemia', 'Horse', 'Non-Core', 'No vaccine available - testing only', 'Annual testing', 'All horses', 'N/A', 'N/A', 'Blood test', 'Coggins test required for transport'),
('Equine Piroplasmosis', 'Horse', 'Non-Core', 'Protects against Babesia caballi and Theileria equi', 'Annual', '6 months and older', 'Various', '2ml', 'Intramuscular', 'Tick-borne blood parasite'),
('Equine Granulocytic Anaplasmosis', 'Horse', 'Non-Core', 'Protects against Anaplasma phagocytophilum', 'Annual', '6 months and older', 'Various', '2ml', 'Intramuscular', 'Tick-borne disease'),
('Equine Monocytic Ehrlichiosis', 'Horse', 'Non-Core', 'Protects against Neorickettsia risticii', 'Annual', '4-6 months, booster 3-4 weeks later', 'Various', '2ml', 'Intramuscular', 'Same as Potomac Horse Fever'),
('Equine Coronavirus', 'Horse', 'Non-Core', 'Protects against equine coronavirus', 'Annual', '6 months and older', 'Various', '2ml', 'Intramuscular', 'Gastrointestinal and respiratory signs'),
('Equine Adenovirus', 'Horse', 'Non-Core', 'Protects against equine adenovirus', 'Annual', '4-6 months and older', 'Various', '2ml', 'Intramuscular', 'Respiratory infection in foals'),
('Equine Arteritis Virus', 'Horse', 'Non-Core', 'Protects against equine viral arteritis', 'Annual', 'Stallions and high-risk mares', 'Various', '1ml', 'Intramuscular', 'Reproductive and respiratory disease'),
('Surra', 'Horse', 'Non-Core', 'Protects against Trypanosoma evansi', 'Annual', '6 months and older', 'Various', '2ml', 'Intramuscular', 'Vector-borne parasitic disease'),
('Dourine', 'Horse', 'Non-Core', 'No vaccine available', 'N/A', 'N/A', 'N/A', 'N/A', 'Eradicated', 'Trypanosoma equiperdum - sexually transmitted'),

-- Rabbit Vaccines
('Rabbit Hemorrhagic Disease Virus (RHDV)', 'Rabbit', 'Core', 'Protects against RHDV causing sudden death', 'Annual', '10-12 weeks, then annual', 'Various', '0.5ml', 'Subcutaneous', 'Essential for all rabbits'),
('RHDV2', 'Rabbit', 'Non-Core', 'Protects against RHDV2 variant', 'Annual', '10-12 weeks, then annual', 'Various', '0.5ml', 'Subcutaneous', 'Newer variant protection'),
('Myxomatosis', 'Rabbit', 'Non-Core', 'Protects against myxomatosis virus', 'Every 6 months', '5-6 weeks, then every 6 months', 'Various', '0.5ml', 'Subcutaneous', 'Important in endemic areas'),
('Pasteurellosis', 'Rabbit', 'Non-Core', 'Protects against Pasteurella multocida', 'Every 6 months', '5-6 weeks and older', 'Various', '0.5ml', 'Subcutaneous', 'Respiratory disease prevention'),
('Rabbit Calicivirus Disease', 'Rabbit', 'Non-Core', 'Protects against RCD virus', 'Annual', '10-12 weeks', 'Various', '0.5ml', 'Subcutaneous', 'Alternative to RHDV'),

-- Ferret Vaccines
('Ferret Rabies', 'Ferret', 'Core', 'Protects against rabies virus', 'Annual', '12-16 weeks, then annual', 'Various', '1ml', 'Subcutaneous', 'Required by law'),
('Ferret Distemper', 'Ferret', 'Core', 'Protects against canine distemper virus', 'Annual', '6-8 weeks, boosters every 3-4 weeks until 14 weeks', 'Various', '1ml', 'Subcutaneous', 'Highly recommended, often fatal'),
('Ferret Influenza', 'Ferret', 'Non-Core', 'Protects against human influenza strains', 'Annual', '12 weeks and older', 'Various', '0.5ml', 'Subcutaneous', 'Ferrets susceptible to human flu'),
('Ferret Adenovirus', 'Ferret', 'Non-Core', 'Protects against ferret adenovirus', 'Annual', '8-12 weeks and older', 'Various', '0.5ml', 'Subcutaneous', 'Respiratory and enteric disease'),
('Ferret Coronavirus', 'Ferret', 'Non-Core', 'Protects against ferret enteric coronavirus', 'Annual', '6-8 weeks and older', 'Various', '0.5ml', 'Subcutaneous', 'Gastrointestinal disease'),
('Ferret Rotavirus', 'Ferret', 'Non-Core', 'Protects against ferret rotavirus', 'Annual', '6-8 weeks and older', 'Various', '0.5ml', 'Subcutaneous', 'Diarrheal disease'),

-- Bird/Poultry Vaccines (Core)
('Marek\'s Disease', 'Bird', 'Core', 'Protects against Marek\'s disease virus', 'Once (day-old)', 'Day 1 of life', 'Various', '0.2ml', 'Subcutaneous', 'Critical for commercial poultry'),
('Newcastle Disease', 'Bird', 'Core', 'Protects against Newcastle disease virus', 'Multiple', '1-7 days, boosters as needed', 'Various', '0.2ml', 'Eye drop/Spray', 'Essential for all poultry'),
('Infectious Bronchitis', 'Bird', 'Core', 'Protects against infectious bronchitis virus', 'Multiple', '1-14 days, boosters as needed', 'Various', '0.2ml', 'Eye drop/Spray', 'Important respiratory protection'),
('Infectious Bursal Disease (Gumboro)', 'Bird', 'Core', 'Protects against IBD virus', 'Multiple', '10-18 days, booster 7-10 days later', 'Various', '0.2ml', 'Drinking water', 'Critical for immune system development'),
('Avian Encephalomyelitis', 'Bird', 'Core', 'Protects against AE virus', 'Once', '10-16 weeks', 'Various', '0.2ml', 'Subcutaneous', 'For breeding flocks'),

-- Bird/Poultry Vaccines (Non-Core)
('Fowl Pox', 'Bird', 'Non-Core', 'Protects against fowl pox virus', 'Annual', '6-10 weeks', 'Various', '0.01ml', 'Wing web', 'For areas with mosquito vectors'),
('Laryngotracheitis', 'Bird', 'Non-Core', 'Protects against infectious laryngotracheitis virus', 'Annual', '4 weeks and older', 'Various', '0.2ml', 'Eye drop', 'For high-risk flocks'),
('Mycoplasma Gallisepticum', 'Bird', 'Non-Core', 'Protects against mycoplasma respiratory infection', 'Multiple', '10-20 weeks', 'Various', '0.2ml', 'Eye drop/Spray', 'For commercial layers'),
('Salmonella Enteritidis', 'Bird', 'Non-Core', 'Protects against salmonella infection', 'Multiple', '1-16 weeks', 'Various', '0.2ml', 'Subcutaneous', 'For commercial layers'),
('E. coli', 'Bird', 'Non-Core', 'Protects against E. coli infection', 'Multiple', '1 day and older', 'Various', '0.2ml', 'Subcutaneous/Spray', 'For high-risk environments'),
('Coryza', 'Bird', 'Non-Core', 'Protects against infectious coryza', 'Annual', '4 weeks and older', 'Various', '0.5ml', 'Subcutaneous', 'For endemic areas'),
('Chicken Anemia Virus', 'Bird', 'Non-Core', 'Protects against chicken anemia virus', 'Once', '10-18 weeks', 'Various', '0.2ml', 'Subcutaneous', 'For breeding flocks'),
('Egg Drop Syndrome', 'Bird', 'Non-Core', 'Protects against EDS-76 virus', 'Annual', '14-16 weeks', 'Various', '0.5ml', 'Subcutaneous', 'For commercial layers'),
('Infectious Coryza', 'Bird', 'Non-Core', 'Protects against Avibacterium paragallinarum', 'Annual', '4-6 weeks, booster 4 weeks later', 'Various', '0.5ml', 'Subcutaneous', 'Respiratory disease'),
('Fowl Cholera', 'Bird', 'Non-Core', 'Protects against Pasteurella multocida', 'Annual', '8-10 weeks', 'Various', '0.5ml', 'Subcutaneous', 'For older birds'),
('Infectious Synovitis', 'Bird', 'Non-Core', 'Protects against Mycoplasma synoviae', 'Annual', '4-6 weeks', 'Various', '0.2ml', 'Subcutaneous', 'Joint and respiratory infection'),
('Turkey Rhinotracheitis', 'Bird', 'Non-Core', 'Protects against TRT virus', 'Annual', '3-4 weeks', 'Various', '0.2ml', 'Eye drop', 'For turkeys'),
('Hemorrhagic Enteritis', 'Bird', 'Non-Core', 'Protects against HE virus', 'Once', '6-11 weeks', 'Various', '0.2ml', 'Drinking water', 'For turkeys'),
('West Nile Virus (Avian)', 'Bird', 'Non-Core', 'Protects birds against West Nile virus', 'Annual', 'Adult birds', 'Various', '0.2ml', 'Subcutaneous', 'For captive birds in endemic areas'),
('Avian Influenza H5N1', 'Bird', 'Non-Core', 'Protects against highly pathogenic avian influenza', 'Annual', '2-3 weeks and older', 'Various', '0.5ml', 'Subcutaneous', 'HPAI, emergency use only'),
('Avian Influenza H7N9', 'Bird', 'Non-Core', 'Protects against H7N9 avian influenza', 'Annual', '2-3 weeks and older', 'Various', '0.5ml', 'Subcutaneous', 'Zoonotic strain'),
('Duck Viral Hepatitis', 'Bird', 'Non-Core', 'Protects against duck hepatitis virus', 'Annual', '1-3 days old', 'Various', '0.2ml', 'Subcutaneous', 'For ducklings'),
('Duck Plague', 'Bird', 'Non-Core', 'Protects against duck enteritis virus', 'Annual', '2-3 weeks and older', 'Various', '0.5ml', 'Subcutaneous', 'Herpesvirus in waterfowl'),
('Goose Parvovirus', 'Bird', 'Non-Core', 'Protects against goose parvovirus', 'Annual', '2-3 weeks and older', 'Various', '0.5ml', 'Subcutaneous', 'Derzsy\\'s disease'),
('Turkey Hemorrhagic Enteritis', 'Bird', 'Non-Core', 'Protects against hemorrhagic enteritis virus', 'Once', '6-11 weeks', 'Various', '0.2ml', 'Drinking water', 'Adenovirus in turkeys'),
('Ornithobacterium Rhinotracheale', 'Bird', 'Non-Core', 'Protects against ORT bacteria', 'Annual', '1-3 weeks and older', 'Various', '0.2ml', 'Subcutaneous', 'Respiratory pathogen'),
('Riemerella Anatipestifer', 'Bird', 'Non-Core', 'Protects against R. anatipestifer', 'Annual', '1-2 weeks and older', 'Various', '0.2ml', 'Subcutaneous', 'Septicemia in waterfowl'),
('Swollen Head Syndrome', 'Bird', 'Non-Core', 'Protects against pneumovirus', 'Annual', '1-3 weeks and older', 'Various', '0.2ml', 'Eye drop', 'Respiratory disease'),
('Inclusion Body Hepatitis', 'Bird', 'Non-Core', 'Protects against fowl adenovirus', 'Annual', '1-3 weeks and older', 'Various', '0.2ml', 'Subcutaneous', 'Adenovirus hepatitis'),

-- Cattle Vaccines (Core)
('Bovine Viral Diarrhea (BVD)', 'Cattle', 'Core', 'Protects against BVD virus', 'Annual', '2-4 months, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Essential for all cattle'),
('Infectious Bovine Rhinotracheitis (IBR)', 'Cattle', 'Core', 'Protects against IBR virus', 'Annual', '2-4 months, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Respiratory protection'),
('Parainfluenza-3 (PI3)', 'Cattle', 'Core', 'Protects against PI3 virus', 'Annual', '2-4 months, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Respiratory complex'),
('Bovine Respiratory Syncytial Virus (BRSV)', 'Cattle', 'Core', 'Protects against BRSV', 'Annual', '2-4 months, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Respiratory protection'),
('Clostridial Diseases (7-way)', 'Cattle', 'Core', 'Protects against multiple clostridial diseases', 'Annual', '2-4 months, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Includes blackleg, malignant edema'),

-- Cattle Vaccines (Non-Core)
('Bovine Leukosis', 'Cattle', 'Non-Core', 'Protects against bovine leukemia virus', 'Annual', '6 months and older', 'Various', '2ml', 'Subcutaneous', 'For high-risk herds'),
('Leptospirosis (5-way)', 'Cattle', 'Non-Core', 'Protects against leptospirosis bacteria', 'Annual', '4-6 months, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'For wet environments'),
('Vibriosis', 'Cattle', 'Non-Core', 'Protects against Campylobacter fetus', 'Annual', 'Breeding bulls and females', 'Various', '2ml', 'Subcutaneous', 'For breeding cattle'),
('Trichomoniasis', 'Cattle', 'Non-Core', 'Protects against Tritrichomonas foetus', 'Annual', 'Breeding bulls and females', 'Various', '2ml', 'Subcutaneous', 'For breeding cattle'),
('Bovine Coronavirus', 'Cattle', 'Non-Core', 'Protects against coronavirus causing scours', 'Annual', '2-4 months, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'For young calves'),
('Bovine Rotavirus', 'Cattle', 'Non-Core', 'Protects against rotavirus causing scours', 'Annual', '2-4 months, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'For young calves'),
('Haemophilus Somnus', 'Cattle', 'Non-Core', 'Protects against H. somnus bacteria', 'Annual', '2-4 months, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Respiratory and reproductive disease'),
('Pasteurella', 'Cattle', 'Non-Core', 'Protects against Pasteurella multocida', 'Annual', '2-4 months, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Respiratory disease complex'),
('Mannheimia Haemolytica', 'Cattle', 'Non-Core', 'Protects against M. haemolytica bacteria', 'Annual', '2-4 months, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Shipping fever prevention'),
('Anaplasmosis', 'Cattle', 'Non-Core', 'Protects against Anaplasma marginale', 'Annual', '4-6 months and older', 'Various', '2ml', 'Subcutaneous', 'Tick-borne blood parasite'),
('Babesiosis', 'Cattle', 'Non-Core', 'Protects against Babesia bovis and B. bigemina', 'Annual', '3-9 months', 'Various', '2ml', 'Subcutaneous', 'Tick fever, live vaccine'),
('Bovine Ephemeral Fever', 'Cattle', 'Non-Core', 'Protects against ephemeral fever virus', 'Annual', '3 months and older', 'Various', '2ml', 'Subcutaneous', 'Three-day sickness'),
('Lumpy Skin Disease', 'Cattle', 'Non-Core', 'Protects against lumpy skin disease virus', 'Annual', '3 months and older', 'Various', '1ml', 'Subcutaneous', 'Poxvirus causing skin lesions'),
('Rift Valley Fever', 'Cattle', 'Non-Core', 'Protects against Rift Valley fever virus', 'Annual', '6 months and older', 'Various', '2ml', 'Subcutaneous', 'Mosquito-borne viral disease'),
('Bovine Tuberculosis', 'Cattle', 'Non-Core', 'BCG vaccine for tuberculosis', 'Once', 'Calves', 'Various', '0.1ml', 'Intradermal', 'Limited use, testing preferred'),
('Johne\\'s Disease', 'Cattle', 'Non-Core', 'Protects against Mycobacterium avium paratuberculosis', 'Once', 'Calves under 35 days', 'Various', '1ml', 'Subcutaneous', 'Chronic wasting disease'),
('Bovine Papillomatosis', 'Cattle', 'Non-Core', 'Protects against bovine papillomavirus', 'Annual', '3 months and older', 'Various', '2ml', 'Subcutaneous', 'Warts and skin tumors'),
('Contagious Bovine Pleuropneumonia', 'Cattle', 'Non-Core', 'Protects against Mycoplasma mycoides', 'Annual', '3 months and older', 'Various', '2ml', 'Subcutaneous', 'Severe respiratory disease'),
('Heartwater', 'Cattle', 'Non-Core', 'Protects against Ehrlichia ruminantium', 'Annual', '3 months and older', 'Various', '1ml', 'Subcutaneous', 'Tick-borne rickettsial disease'),

-- Sheep/Goat Vaccines (Core)
('Clostridial Diseases (8-way)', 'Sheep', 'Core', 'Protects against multiple clostridial diseases', 'Annual', '6-8 weeks, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Essential for all sheep'),
('Clostridial Diseases (8-way)', 'Goat', 'Core', 'Protects against multiple clostridial diseases', 'Annual', '6-8 weeks, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Essential for all goats'),
('Ovine/Caprine Tetanus', 'Sheep', 'Core', 'Protects against tetanus bacteria', 'Annual', '6-8 weeks, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Essential protection'),
('Ovine/Caprine Tetanus', 'Goat', 'Core', 'Protects against tetanus bacteria', 'Annual', '6-8 weeks, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Essential protection'),

-- Sheep/Goat Vaccines (Non-Core)
('Caseous Lymphadenitis', 'Sheep', 'Non-Core', 'Protects against CL bacteria', 'Annual', '2-4 months, booster 2-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'For endemic areas'),
('Caseous Lymphadenitis', 'Goat', 'Non-Core', 'Protects against CL bacteria', 'Annual', '2-4 months, booster 2-4 weeks later', 'Various', '1ml', 'Subcutaneous', 'For endemic areas'),
('Ovine Progressive Pneumonia', 'Sheep', 'Non-Core', 'Protects against OPP virus', 'Annual', '2-4 months and older', 'Various', '1ml', 'Subcutaneous', 'For high-risk flocks'),
('Caprine Arthritis Encephalitis', 'Goat', 'Non-Core', 'Protects against CAE virus', 'Annual', '2-4 months and older', 'Various', '1ml', 'Subcutaneous', 'For high-risk herds'),
('Footrot', 'Sheep', 'Non-Core', 'Protects against Dichelobacter nodosus', 'Annual', '6 weeks and older', 'Various', '1ml', 'Subcutaneous', 'For wet, muddy conditions'),
('Footrot', 'Goat', 'Non-Core', 'Protects against Dichelobacter nodosus', 'Annual', '6 weeks and older', 'Various', '1ml', 'Subcutaneous', 'For wet, muddy conditions'),
('Contagious Ecthyma (Sore Mouth)', 'Sheep', 'Non-Core', 'Protects against orf virus', 'Annual', '2-4 months', 'Various', 'Scarification', 'Skin scarification', 'Live virus vaccine'),
('Contagious Ecthyma (Sore Mouth)', 'Goat', 'Non-Core', 'Protects against orf virus', 'Annual', '2-4 months', 'Various', 'Scarification', 'Skin scarification', 'Live virus vaccine'),
('Chlamydial Abortion', 'Sheep', 'Non-Core', 'Protects against Chlamydia abortus', 'Annual', 'Before breeding', 'Various', '2ml', 'Subcutaneous', 'For breeding ewes'),
('Chlamydial Abortion', 'Goat', 'Non-Core', 'Protects against Chlamydia abortus', 'Annual', 'Before breeding', 'Various', '2ml', 'Subcutaneous', 'For breeding does'),
('Bluetongue', 'Sheep', 'Non-Core', 'Protects against bluetongue virus', 'Annual', '3 months and older', 'Various', '1ml', 'Subcutaneous', 'Midge-borne viral disease'),
('Scrapie', 'Sheep', 'Non-Core', 'No vaccine available - genetic resistance', 'N/A', 'N/A', 'N/A', 'N/A', 'Genetic', 'Prion disease, breeding for resistance'),
('Maedi-Visna', 'Sheep', 'Non-Core', 'No effective vaccine available', 'N/A', 'N/A', 'N/A', 'N/A', 'Control', 'Lentivirus, control through testing'),
('Border Disease', 'Sheep', 'Non-Core', 'Protects against border disease virus', 'Annual', 'Before breeding', 'Various', '2ml', 'Subcutaneous', 'Pestivirus causing reproductive problems'),
('Louping Ill', 'Sheep', 'Non-Core', 'Protects against louping ill virus', 'Annual', '6 months and older', 'Various', '1ml', 'Subcutaneous', 'Tick-borne encephalitis'),
('Sheep Pox', 'Sheep', 'Non-Core', 'Protects against sheep pox virus', 'Annual', '3 months and older', 'Various', '0.5ml', 'Subcutaneous', 'Poxvirus causing skin lesions'),
('Nairobi Sheep Disease', 'Sheep', 'Non-Core', 'Protects against Nairobi sheep disease virus', 'Annual', '3 months and older', 'Various', '1ml', 'Subcutaneous', 'Tick-borne hemorrhagic fever'),
('Peste des Petits Ruminants', 'Sheep', 'Non-Core', 'Protects against PPR virus', 'Annual', '4 months and older', 'Various', '1ml', 'Subcutaneous', 'Morbillivirus, goat plague'),
('Ovine Herpesvirus', 'Sheep', 'Non-Core', 'Protects against ovine herpesvirus-2', 'Annual', '6 months and older', 'Various', '2ml', 'Subcutaneous', 'Causes malignant catarrhal fever in cattle'),
('Q Fever', 'Sheep', 'Non-Core', 'Protects against Coxiella burnetii', 'Annual', 'Before breeding', 'Various', '1ml', 'Subcutaneous', 'Zoonotic rickettsial disease'),
('Caprine Pleuropneumonia', 'Goat', 'Non-Core', 'Protects against Mycoplasma capricolum', 'Annual', '3 months and older', 'Various', '2ml', 'Subcutaneous', 'Contagious respiratory disease'),
('Goat Pox', 'Goat', 'Non-Core', 'Protects against goat pox virus', 'Annual', '3 months and older', 'Various', '0.5ml', 'Subcutaneous', 'Poxvirus causing skin lesions'),
('Caprine Herpesvirus', 'Goat', 'Non-Core', 'Protects against caprine herpesvirus-1', 'Annual', '6 months and older', 'Various', '1ml', 'Subcutaneous', 'Respiratory and reproductive disease'),
('Paratuberculosis (Goats)', 'Goat', 'Non-Core', 'Protects against Mycobacterium avium paratuberculosis', 'Once', 'Kids under 35 days', 'Various', '1ml', 'Subcutaneous', 'Johne\\'s disease in goats'),
('Caprine Coronavirus', 'Goat', 'Non-Core', 'Protects against caprine coronavirus', 'Annual', '2-4 months and older', 'Various', '2ml', 'Subcutaneous', 'Diarrhea in young goats'),
('Caprine Rotavirus', 'Goat', 'Non-Core', 'Protects against caprine rotavirus', 'Annual', '2-4 months and older', 'Various', '2ml', 'Subcutaneous', 'Diarrhea in kids'),
('Caprine Adenovirus', 'Goat', 'Non-Core', 'Protects against caprine adenovirus', 'Annual', '2-4 months and older', 'Various', '1ml', 'Subcutaneous', 'Respiratory disease in kids'),
('Enzootic Abortion', 'Goat', 'Non-Core', 'Protects against Chlamydia abortus', 'Annual', 'Before breeding', 'Various', '2ml', 'Subcutaneous', 'Reproductive disease'),
('Toxoplasmosis', 'Goat', 'Non-Core', 'Protects against Toxoplasma gondii', 'Annual', 'Before breeding', 'Various', '2ml', 'Subcutaneous', 'Protozoal abortion'),
('Neosporosis', 'Goat', 'Non-Core', 'Protects against Neospora caninum', 'Annual', 'Before breeding', 'Various', '2ml', 'Subcutaneous', 'Protozoal abortion'),

-- Swine Vaccines (Core)
('Porcine Reproductive and Respiratory Syndrome (PRRS)', 'Pig', 'Core', 'Protects against PRRS virus', 'Annual', '3-4 weeks, booster 2-3 weeks later', 'Various', '2ml', 'Intramuscular', 'Major swine disease'),
('Porcine Circovirus Type 2 (PCV2)', 'Pig', 'Core', 'Protects against PCV2 virus', 'Annual', '3-4 weeks, booster 2-3 weeks later', 'Various', '2ml', 'Intramuscular', 'Important for growth'),
('Mycoplasma Hyopneumoniae', 'Pig', 'Core', 'Protects against mycoplasma pneumonia', 'Annual', '1-3 weeks, booster 2-3 weeks later', 'Various', '2ml', 'Intramuscular', 'Respiratory protection'),

-- Swine Vaccines (Non-Core)
('Swine Influenza', 'Pig', 'Non-Core', 'Protects against swine influenza virus', 'Every 6 months', '3-4 weeks, booster 2-3 weeks later', 'Various', '2ml', 'Intramuscular', 'For high-risk herds'),
('Porcine Parvovirus', 'Pig', 'Non-Core', 'Protects against parvovirus', 'Annual', 'Breeding sows and gilts', 'Various', '2ml', 'Intramuscular', 'For breeding animals'),
('Erysipelas', 'Pig', 'Non-Core', 'Protects against erysipelas bacteria', 'Annual', '8-10 weeks, booster 2-3 weeks later', 'Various', '2ml', 'Intramuscular', 'For outdoor pigs'),
('Atrophic Rhinitis', 'Pig', 'Non-Core', 'Protects against Bordetella bronchiseptica and Pasteurella multocida', 'Annual', '1-3 weeks, booster 2-4 weeks later', 'Various', '2ml', 'Intramuscular', 'Nasal turbinate protection'),
('Transmissible Gastroenteritis (TGE)', 'Pig', 'Non-Core', 'Protects against TGE coronavirus', 'Annual', 'Pregnant sows', 'Various', '2ml', 'Intramuscular', 'For breeding sows'),
('Porcine Epidemic Diarrhea (PED)', 'Pig', 'Non-Core', 'Protects against PED coronavirus', 'Annual', 'Pregnant sows', 'Various', '2ml', 'Intramuscular', 'For breeding sows'),
('Glässer\\'s Disease', 'Pig', 'Non-Core', 'Protects against Haemophilus parasuis', 'Annual', '3-4 weeks, booster 2-3 weeks later', 'Various', '2ml', 'Intramuscular', 'Systemic infection prevention'),
('Swine Dysentery', 'Pig', 'Non-Core', 'Protects against Brachyspira hyodysenteriae', 'Annual', '6-8 weeks and older', 'Various', '2ml', 'Intramuscular', 'For endemic farms'),
('African Swine Fever', 'Pig', 'Non-Core', 'No effective vaccine available', 'N/A', 'N/A', 'N/A', 'N/A', 'Control', 'Highly contagious viral disease'),
('Classical Swine Fever', 'Pig', 'Non-Core', 'Protects against classical swine fever virus', 'Annual', '6-8 weeks and older', 'Various', '2ml', 'Intramuscular', 'Hog cholera, live vaccine'),
('Swine Vesicular Disease', 'Pig', 'Non-Core', 'Protects against swine vesicular disease virus', 'Annual', '8-10 weeks and older', 'Various', '2ml', 'Intramuscular', 'Vesicular disease'),
('Foot-and-Mouth Disease', 'Pig', 'Non-Core', 'Protects against FMD virus', 'Every 6 months', '2-4 months and older', 'Various', '2ml', 'Intramuscular', 'Highly contagious vesicular disease'),
('Pseudorabies (Aujeszky\\'s)', 'Pig', 'Non-Core', 'Protects against pseudorabies virus', 'Annual', '6-8 weeks, booster 2-3 weeks later', 'Various', '2ml', 'Intramuscular', 'Herpesvirus, eradicated in many countries'),
('Swine Pox', 'Pig', 'Non-Core', 'Protects against swine pox virus', 'Annual', '4-6 weeks and older', 'Various', '1ml', 'Subcutaneous', 'Poxvirus causing skin lesions'),
('Japanese Encephalitis', 'Pig', 'Non-Core', 'Protects against Japanese encephalitis virus', 'Annual', '2-3 months and older', 'Various', '1ml', 'Subcutaneous', 'Mosquito-borne encephalitis'),
('Getah Virus', 'Pig', 'Non-Core', 'Protects against Getah virus', 'Annual', '2-3 months and older', 'Various', '2ml', 'Intramuscular', 'Mosquito-borne alphavirus'),
('Porcine Teschovirus', 'Pig', 'Non-Core', 'Protects against porcine teschovirus', 'Annual', '4-6 weeks and older', 'Various', '2ml', 'Intramuscular', 'Enteric and nervous system disease'),

-- Fish Vaccines
('Vibriosis', 'Fish', 'Core', 'Protects against Vibrio anguillarum', 'Annual', 'Fingerling stage', 'Various', 'Bath/Injection', 'Immersion/Injection', 'Major bacterial disease'),
('Furunculosis', 'Fish', 'Core', 'Protects against Aeromonas salmonicida', 'Annual', 'Fingerling stage', 'Various', 'Bath/Injection', 'Immersion/Injection', 'Bacterial skin disease'),
('Infectious Pancreatic Necrosis (IPN)', 'Fish', 'Non-Core', 'Protects against IPN virus', 'Annual', 'Fry stage', 'Various', 'Bath', 'Immersion', 'Viral disease of young fish'),
('Viral Hemorrhagic Septicemia (VHS)', 'Fish', 'Non-Core', 'Protects against VHS virus', 'Annual', 'Fingerling stage', 'Various', 'Bath/Injection', 'Immersion/Injection', 'Serious viral disease'),
('Infectious Salmon Anemia (ISA)', 'Fish', 'Non-Core', 'Protects against ISA virus', 'Annual', 'Smolt stage', 'Various', 'Injection', 'Injection', 'For salmon species'),
('Spring Viremia of Carp', 'Fish', 'Non-Core', 'Protects against SVC rhabdovirus', 'Annual', 'Fingerling stage', 'Various', 'Bath', 'Immersion', 'Viral disease of cyprinids'),
('Koi Herpesvirus', 'Fish', 'Non-Core', 'Protects against KHV/CyHV-3', 'Annual', 'Fingerling stage', 'Various', 'Bath', 'Immersion', 'Cyprinid herpesvirus 3'),
('Viral Nervous Necrosis', 'Fish', 'Non-Core', 'Protects against VNN nodavirus', 'Annual', 'Larval/juvenile stage', 'Various', 'Bath', 'Immersion', 'Nervous system disease'),
('Infectious Hematopoietic Necrosis', 'Fish', 'Non-Core', 'Protects against IHN rhabdovirus', 'Annual', 'Fry stage', 'Various', 'Bath/Injection', 'Immersion/Injection', 'Salmonid viral disease'),
('Bacterial Kidney Disease', 'Fish', 'Non-Core', 'Protects against Renibacterium salmoninarum', 'Annual', 'Fingerling stage', 'Various', 'Injection', 'Injection', 'Chronic bacterial infection'),
('Columnaris Disease', 'Fish', 'Non-Core', 'Protects against Flavobacterium columnare', 'Annual', 'Fingerling stage', 'Various', 'Bath', 'Immersion', 'Bacterial skin disease'),
('Enteric Redmouth Disease', 'Fish', 'Non-Core', 'Protects against Yersinia ruckeri', 'Annual', 'Fingerling stage', 'Various', 'Bath/Injection', 'Immersion/Injection', 'Bacterial septicemia'),
('Streptococcosis', 'Fish', 'Non-Core', 'Protects against Streptococcus species', 'Annual', 'Fingerling stage', 'Various', 'Bath/Injection', 'Immersion/Injection', 'Bacterial infection'),
('Lactococcosis', 'Fish', 'Non-Core', 'Protects against Lactococcus garvieae', 'Annual', 'Fingerling stage', 'Various', 'Bath/Injection', 'Immersion/Injection', 'Bacterial septicemia'),
('Photobacteriosis', 'Fish', 'Non-Core', 'Protects against Photobacterium damselae', 'Annual', 'Fingerling stage', 'Various', 'Bath/Injection', 'Immersion/Injection', 'Marine bacterial disease'),

-- Exotic Animal Vaccines
('Llama/Alpaca CDT', 'Llama', 'Core', 'Protects against clostridial diseases', 'Annual', '6-8 weeks, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Essential for camelids'),
('Llama/Alpaca CDT', 'Alpaca', 'Core', 'Protects against clostridial diseases', 'Annual', '6-8 weeks, booster 2-4 weeks later', 'Various', '2ml', 'Subcutaneous', 'Essential for camelids'),
('Meningeal Worm Prevention', 'Llama', 'Non-Core', 'Protects against Parelaphostrongylus tenuis', 'Annual', '6 months and older', 'Various', '1ml', 'Subcutaneous', 'For areas with white-tailed deer'),
('Meningeal Worm Prevention', 'Alpaca', 'Non-Core', 'Protects against Parelaphostrongylus tenuis', 'Annual', '6 months and older', 'Various', '1ml', 'Subcutaneous', 'For areas with white-tailed deer'),
('Chinchilla Pasteurellosis', 'Chinchilla', 'Non-Core', 'Protects against Pasteurella multocida', 'Annual', '8 weeks and older', 'Various', '0.2ml', 'Subcutaneous', 'Respiratory infection'),
('Guinea Pig Adenovirus', 'Guinea Pig', 'Non-Core', 'Protects against guinea pig adenovirus', 'Annual', '4-6 weeks and older', 'Various', '0.2ml', 'Subcutaneous', 'Respiratory disease'),
('Hamster Polyomavirus', 'Hamster', 'Non-Core', 'Protects against hamster polyomavirus', 'Annual', '4-6 weeks and older', 'Various', '0.1ml', 'Subcutaneous', 'Tumor-causing virus'),
('Gerbil Tyzzer\\'s Disease', 'Gerbil', 'Non-Core', 'Protects against Clostridium piliforme', 'Annual', '4-6 weeks and older', 'Various', '0.1ml', 'Subcutaneous', 'Enteric bacterial disease'),
('Rat Coronavirus', 'Rat', 'Non-Core', 'Protects against rat coronavirus', 'Annual', '4-6 weeks and older', 'Various', '0.2ml', 'Subcutaneous', 'Respiratory disease'),
('Mouse Hepatitis Virus', 'Mouse', 'Non-Core', 'Protects against mouse hepatitis virus', 'Annual', '4-6 weeks and older', 'Various', '0.1ml', 'Subcutaneous', 'Coronavirus causing hepatitis'),
('Hedgehog Wobbly Hedgehog Syndrome', 'Hedgehog', 'Non-Core', 'No vaccine available', 'N/A', 'N/A', 'N/A', 'N/A', 'Supportive', 'Progressive neurological disease');
